#ifndef JS_ENGINE_STACK_POINTERS_H
#define JS_ENGINE_STACK_POINTERS_H
#define STACK_ADDR_RETURN "___RETURN___"
#define STACK_ADDR_CONSTRUCT_FLAG "___NEW___"
#define STACK_ADDR_CONSTRUCT_CALLER "___NEW_CALLER___"
#define STACK_ADDR_THIS "this"
#define STACK_ADDR_EXCEPTION "___EXCEPTION___"
#endif
